version: '3.8'

services:
  incident-api:
    build: .
    container_name: incident-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://root:example@mongo/
      PORT: 3000
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_USER: ${MAIL_USER}
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: